--CREATE DATABASE ShopEase;

USE ShopEase;

--Creating the Tables
CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
JOIN_DATE DATE NOT NULL,
IS_PREMIUM BIT DEFAULT 0
);

CREATE INDEX IDX_CUSTOMERS_CITY ON CUSTOMERS(CITY);
CREATE INDEX IDX_CUSTOMERS_STATE ON CUSTOMERS(STATE);

--Creating table Products
CREATE TABLE PRODUCTS(
PRODUCT_ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR(50) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
BRAND VARCHAR(50),
UNIT_PRICE DECIMAL(10,2) NOT NULL
CHECK (UNIT_PRICE > 0),
STOCK_QTY INT NOT NULL DEFAULT 0
CHECK (STOCK_QTY >= 0));

--Creating the index on the table
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY);

--Creating orders table
CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
ORDER_DATE DATE NOT NULL,
ORDER_STATUS VARCHAR(20) NOT NULL DEFAULT 'Pending'
CHECK (ORDER_STATUS IN('Pending', 'Shipped', 'Delivered', 'Cancelled')),
TOTAL_AMOUNT DECIMAL(12,2) NOT NULL
CHECK (TOTAL_AMOUNT >= 0),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID));

--Creating Order_Items table
CREATE TABLE ORDER_ITEMS(
ITEM_ID INT PRIMARY KEY,
ORDER_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
QUANTITY INT NOT NULL
CHECK (QUANTITY > 0),
UNIT_PRICE DECIMAL(10,2) NOT NULL
CHECK (UNIT_PRICE > 0),
DISCOUNT_PCT DECIMAL(5,2) DEFAULT 0
CHECK (DISCOUNT_PCT BETWEEN 0 AND 100),
FOREIGN KEY(ORDER_ID) REFERENCES ORDERS (ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID));