USE SuperstoreDB;

--Creating CUSTOMERS table
CREATE TABLE CUSTOMERS
(
CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(100),
SEGMENT VARCHAR(30)
);

--Creating PRODUCTS table
CREATE TABLE PRODUCTS
(
PRODUCT_ID VARCHAR(30),
PRODUCT_NAME VARCHAR(200),
CATEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50)
);

--Creating ORDERS table
CREATE TABLE ORDERS
(
ROW_ID INT,
ORDER_ID VARCHAR(30),
ORDER_DATE DATE,
SHIP_DATE DATE,
SHIP_MODE VARCHAR(50),
CUSTOMER_ID VARCHAR(20),
COUNTRY VARCHAR(50),
CITY VARCHAR(50),
STATE_NAME VARCHAR(50),
POSTAL_CODE INT,
REGION VARCHAR(30),
PRODUCT_ID VARCHAR(30),
SALES DECIMAL(10,2),
QUANTITY INT,
DISCOUNT DECIMAL(5,2),
PROFIT DECIMAL(10,2)
);

/*Inserting values into CUSTOMERS table,
  by extracting from superstore dataset */

  INSERT INTO CUSTOMERS
  SELECT DISTINCT 
  [CUSTOMER_ID],
  [CUSTOMER_NAME],
  SEGMENT
  FROM SUPERSTORE_RAW;


/*Inserting values into PRODUCTS table,
  by extracting from superstore dataset */ 
INSERT INTO Products
SELECT DISTINCT
    [Product_ID],
    [Product_Name],
    Category,
    [Sub_Category]
FROM superstore_raw;

/*Inserting values into ORDERS table,
  by extracting from superstore dataset */ 
 INSERT INTO Orders
(
    ROW_ID,
    ORDER_ID,
    ORDER_DATE,
    SHIP_DATE,
    SHIP_MODE,
    CUSTOMER_ID,
    COUNTRY,
    CITY,
    STATE_NAME,
    POSTAL_CODE,
    REGION,
    PRODUCT_ID,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT
)
SELECT
    ROW_ID,
    ORDER_ID,
    TRY_CONVERT(DATE, ORDER_DATE, 101),
    TRY_CONVERT(DATE, SHIP_DATE, 101),
    SHIP_MODE,
    CUSTOMER_ID,
    COUNTRY,
    CITY,
    STATE,
    POSTAL_CODE,
    REGION,
    PRODUCT_ID,
    SALES,
    QUANTITY,
    DISCOUNT,
    PROFIT
FROM SUPERSTORE_RAW;